# Use the official Node.js image as the base image for frontend
FROM node:20.0.0-alpine AS backend

# Set the working directory for frontend
WORKDIR /app/quirknotes/backend

# Copy frontend package files
COPY quirknotes/backend/package*.json ./

# Install backend dependencies
RUN npm install

# Copy frontend source code
COPY quirknotes/backend ./

# Build frontenddsadas
#RUN npm run build

# Build backend if necessary, or compile TypeScript to JavaScript, etc.
#RUN npm run build

# Expose the port the backend runs on
EXPOSE 3001

# Command to start the backend application
CMD ["npm", "start"]
